package com.preventsgm;

import net.runelite.api.gameval.ItemID;

public class IsTeleportItem {

    public static boolean isWearableParam1 (int param1) {
        switch (param1) {
            case 25362447: //Helmet
            case 25362448: //Cape
            case 25362457: //Pocket slot
            case 25362456: //Ring
            case 25362449: //Necklace
            case 25362455: //Boots
            case 25362452: //Off hand
            case 25362450: //Main hand
            case 25362454: //Gloves
            case 25362451: //Chest plate
            case 25362453: //legs
                return true;
        }
        return false;
    }

    /**
     *
     * Sigh... I have no clue how to otherwise determine the player is trying to teleport if it doesn't say in the item's name or menu action "Teleport"
     * @param itemID the items id
     * @return true if it's an item you use to teleport, otherwise false
     */
    public static boolean itemIsTeleportItem (int itemID) {
        switch (itemID) {
            //Script found these automatically
            case ItemID.ALUFT_SEED_POD:
            case ItemID.AMULET_OF_GLORY_1:
            case ItemID.AMULET_OF_GLORY_2:
            case ItemID.AMULET_OF_GLORY_3:
            case ItemID.AMULET_OF_GLORY_4:
            case ItemID.AMULET_OF_GLORY_5:
            case ItemID.AMULET_OF_GLORY_6:
            case ItemID.AMULET_OF_GLORY_INF:
            case ItemID.ARDY_CAPE_EASY:
            case ItemID.ARDY_CAPE_ELITE:
            case ItemID.ARDY_CAPE_HARD:
            case ItemID.ARDY_CAPE_MEDIUM:
            case ItemID.ATJUN_GLOVES_ELITE:
            case ItemID.ATJUN_GLOVES_HARD:
            case ItemID.BOOKOFSCROLLS_CHARGED:
            case ItemID.BOOK_OF_THE_DEAD:
            case ItemID.BR_AMULET_OF_GLORY:
            case ItemID.BURNING_AMULET_1:
            case ItemID.BURNING_AMULET_2:
            case ItemID.BURNING_AMULET_3:
            case ItemID.BURNING_AMULET_4:
            case ItemID.BURNING_AMULET_5:
            case ItemID.CAMULET:
            case ItemID.CA_OFFHAND_EASY:
            case ItemID.CA_OFFHAND_ELITE:
            case ItemID.CA_OFFHAND_GRANDMASTER:
            case ItemID.CA_OFFHAND_HARD:
            case ItemID.CA_OFFHAND_MASTER:
            case ItemID.CA_OFFHAND_MEDIUM:
            case ItemID.CHRONICLE:
            case ItemID.DEADMAN_TOURNAMENT_TELETAB:
            case ItemID.DESERT_AMULET_ELITE:
            case ItemID.DESERT_AMULET_HARD:
            case ItemID.DESERT_AMULET_MEDIUM:
            case ItemID.DISCOFRETURNING:
            case ItemID.DORGESH_TELEPORT_ARTIFACT:
            case ItemID.DRAKANS_MEDALLION:
            case ItemID.ECTOPHIAL_EMPTY:
            case ItemID.ELF_CRYSTAL_TINY:
            case ItemID.FOSSIL_TABLET_VOLCANOTELEPORT:
            case ItemID.FREMENNIK_BOOTS_EASY:
            case ItemID.FREMENNIK_BOOTS_ELITE:
            case ItemID.FREMENNIK_BOOTS_HARD:
            case ItemID.FREMENNIK_BOOTS_MEDIUM:
            case ItemID.GAUNTLET_TELEPORT_CRYSTAL:
            case ItemID.GIANTSOUL_AMULET_CHARGED:
            case ItemID.HALLOWED_TELEPORT:
            case ItemID.HG_QUETZALWHISTLE_BASIC:
            case ItemID.HG_QUETZALWHISTLE_ENHANCED:
            case ItemID.HG_QUETZALWHISTLE_PERFECTED:
            case ItemID.INFERNAL_DEFENDER_GHOMMAL_5:
            case ItemID.INFERNAL_DEFENDER_GHOMMAL_6:
            case ItemID.JEWL_BRACELET_OF_COMBAT:
            case ItemID.JEWL_BRACELET_OF_COMBAT_1:
            case ItemID.JEWL_BRACELET_OF_COMBAT_2:
            case ItemID.JEWL_BRACELET_OF_COMBAT_3:
            case ItemID.JEWL_BRACELET_OF_COMBAT_4:
            case ItemID.JEWL_BRACELET_OF_COMBAT_5:
            case ItemID.JEWL_BRACELET_OF_COMBAT_6:
            case ItemID.JEWL_NECKLACE_OF_SKILLS:
            case ItemID.JEWL_NECKLACE_OF_SKILLS_1:
            case ItemID.JEWL_NECKLACE_OF_SKILLS_2:
            case ItemID.JEWL_NECKLACE_OF_SKILLS_3:
            case ItemID.JEWL_NECKLACE_OF_SKILLS_4:
            case ItemID.JEWL_NECKLACE_OF_SKILLS_5:
            case ItemID.JEWL_NECKLACE_OF_SKILLS_6:
            case ItemID.LOTG_TELEPORT_ARTIFACT:
            case ItemID.LUMBRIDGE_RING_ELITE:
            case ItemID.LUMBRIDGE_RING_HARD:
            case ItemID.LUMBRIDGE_RING_MEDIUM:
            case ItemID.LUNAR_TABLET_BARBARIAN_TELEPORT:
            case ItemID.LUNAR_TABLET_CATHERBY_TELEPORT:
            case ItemID.LUNAR_TABLET_FISHING_GUILD_TELEPORT:
            case ItemID.LUNAR_TABLET_ICE_PLATEAU_TELEPORT:
            case ItemID.LUNAR_TABLET_KHAZARD_TELEPORT:
            case ItemID.LUNAR_TABLET_MOONCLAN_TELEPORT:
            case ItemID.LUNAR_TABLET_OURANIA_TELEPORT:
            case ItemID.LUNAR_TABLET_WATERBIRTH_TELEPORT:
            case ItemID.MAGIC_STRUNG_LYRE:
            case ItemID.MAGIC_STRUNG_LYRE_2:
            case ItemID.MAGIC_STRUNG_LYRE_3:
            case ItemID.MAGIC_STRUNG_LYRE_4:
            case ItemID.MAGIC_STRUNG_LYRE_5:
            case ItemID.MAGIC_STRUNG_LYRE_INFINITE:
            case ItemID.MAGIC_WHISTLE:
            case ItemID.MM2_ROYAL_SEED_POD:
            case ItemID.MM_SIGIL:
            case ItemID.MORYTANIA_LEGS_EASY:
            case ItemID.MORYTANIA_LEGS_ELITE:
            case ItemID.MORYTANIA_LEGS_HARD:
            case ItemID.MORYTANIA_LEGS_MEDIUM:
            case ItemID.MOURNING_TELEPORT_CRYSTAL_1:
            case ItemID.MOURNING_TELEPORT_CRYSTAL_2:
            case ItemID.MOURNING_TELEPORT_CRYSTAL_3:
            case ItemID.MOURNING_TELEPORT_CRYSTAL_4:
            case ItemID.MOURNING_TELEPORT_CRYSTAL_5:
            case ItemID.MUSIC_CAPE:
            case ItemID.MYTHICAL_CAPE:
            case ItemID.NECKLACE_OF_DIGSITE_1:
            case ItemID.NECKLACE_OF_DIGSITE_2:
            case ItemID.NECKLACE_OF_DIGSITE_3:
            case ItemID.NECKLACE_OF_DIGSITE_4:
            case ItemID.NECKLACE_OF_DIGSITE_5:
            case ItemID.NECKLACE_OF_MINIGAMES_1:
            case ItemID.NECKLACE_OF_MINIGAMES_2:
            case ItemID.NECKLACE_OF_MINIGAMES_3:
            case ItemID.NECKLACE_OF_MINIGAMES_4:
            case ItemID.NECKLACE_OF_MINIGAMES_5:
            case ItemID.NECKLACE_OF_MINIGAMES_6:
            case ItemID.NECKLACE_OF_MINIGAMES_7:
            case ItemID.NECKLACE_OF_MINIGAMES_8:
            case ItemID.NECKLACE_OF_PASSAGE_1:
            case ItemID.NECKLACE_OF_PASSAGE_2:
            case ItemID.NECKLACE_OF_PASSAGE_3:
            case ItemID.NECKLACE_OF_PASSAGE_4:
            case ItemID.NECKLACE_OF_PASSAGE_5:
            case ItemID.NZONE_TELETAB_ALDARIN:
            case ItemID.NZONE_TELETAB_BRIMHAVEN:
            case ItemID.NZONE_TELETAB_KOUREND:
            case ItemID.NZONE_TELETAB_POLLNIVNEACH:
            case ItemID.NZONE_TELETAB_RELLEKKA:
            case ItemID.NZONE_TELETAB_RIMMINGTON:
            case ItemID.NZONE_TELETAB_TAVERLEY:
            case ItemID.NZONE_TELETAB_TROLLHEIM:
            case ItemID.NZONE_TELETAB_YANILLE:
            case ItemID.PENDANT_OF_ATES:
            case ItemID.PHARAOHS_SCEPTRE_CHARGED_INITIAL:
            case ItemID.POH_TABLET_ARDOUGNETELEPORT:
            case ItemID.POH_TABLET_CAMELOTTELEPORT:
            case ItemID.POH_TABLET_FALADORTELEPORT:
            case ItemID.POH_TABLET_FORTISTELEPORT:
            case ItemID.POH_TABLET_KOURENDTELEPORT:
            case ItemID.POH_TABLET_LUMBRIDGETELEPORT:
            case ItemID.POH_TABLET_TELEPORTTOHOUSE:
            case ItemID.POH_TABLET_VARROCKTELEPORT:
            case ItemID.POH_TABLET_WATCHTOWERTELEPORT:
            case ItemID.PRIF_TELEPORT_CRYSTAL:
            case ItemID.RATCATCHERS_PARTY_DIRECTIONS:
            case ItemID.RING_OF_DUELING_1:
            case ItemID.RING_OF_DUELING_2:
            case ItemID.RING_OF_DUELING_3:
            case ItemID.RING_OF_DUELING_4:
            case ItemID.RING_OF_DUELING_5:
            case ItemID.RING_OF_DUELING_6:
            case ItemID.RING_OF_DUELING_7:
            case ItemID.RING_OF_DUELING_8:
            case ItemID.RING_OF_ELEMENTS_CHARGED:
            case ItemID.RING_OF_LIFE:
            case ItemID.RING_OF_RETURNING_1:
            case ItemID.RING_OF_RETURNING_2:
            case ItemID.RING_OF_RETURNING_3:
            case ItemID.RING_OF_RETURNING_4:
            case ItemID.RING_OF_RETURNING_5:
            case ItemID.RING_OF_WEALTH:
            case ItemID.RING_OF_WEALTH_1:
            case ItemID.RING_OF_WEALTH_2:
            case ItemID.RING_OF_WEALTH_3:
            case ItemID.RING_OF_WEALTH_4:
            case ItemID.RING_OF_WEALTH_5:
            case ItemID.RING_OF_WEALTH_I:
            case ItemID.SEERS_HEADBAND_ELITE:
            case ItemID.SEERS_HEADBAND_HARD:
            case ItemID.SKILLCAPE_AD:
            case ItemID.SKILLCAPE_CONSTRUCTION:
            case ItemID.SKILLCAPE_CRAFTING:
            case ItemID.SKILLCAPE_DEFENCE:
            case ItemID.SKILLCAPE_FARMING:
            case ItemID.SKILLCAPE_FISHING:
            case ItemID.SKILLCAPE_HUNTING:
            case ItemID.SKILLCAPE_MAX_ARDY:
            case ItemID.SKILLCAPE_MAX_MYTHICAL:
            case ItemID.SKILLCAPE_MAX_WORN:
            case ItemID.SKILLCAPE_QP:
            case ItemID.SKILLCAPE_STRENGTH:
            case ItemID.SLAYER_RING_1:
            case ItemID.SLAYER_RING_2:
            case ItemID.SLAYER_RING_3:
            case ItemID.SLAYER_RING_4:
            case ItemID.SLAYER_RING_5:
            case ItemID.SLAYER_RING_6:
            case ItemID.SLAYER_RING_7:
            case ItemID.SLAYER_RING_8:
            case ItemID.SLAYER_RING_ETERNAL:
            case ItemID.SLICE_TELEPORT_ARTIFACT:
            case ItemID.SOS_SKULL_SCEPTRE:
            case ItemID.SOS_SKULL_SCEPTRE_IMBUED:
            case ItemID.STRONGHOLD_TELEPORT_BASALT:
            case ItemID.TABLET_ANNAKARL:
            case ItemID.TABLET_CARRALLANGAR:
            case ItemID.TABLET_DAREEYAK:
            case ItemID.TABLET_GHORROCK:
            case ItemID.TABLET_KHARYLL:
            case ItemID.TABLET_LASSAR:
            case ItemID.TABLET_PADDEWA:
            case ItemID.TABLET_SENNTISTEN:
            case ItemID.TABLET_TARGET:
            case ItemID.TABLET_WILDYCRABS:
            case ItemID.TELEPORTSCROLL_CERBERUS:
            case ItemID.TELEPORTSCROLL_CHASMOFFIRE:
            case ItemID.TELEPORTSCROLL_COLOSSAL_WYRM:
            case ItemID.TELEPORTSCROLL_DIGSITE:
            case ItemID.TELEPORTSCROLL_ELF:
            case ItemID.TELEPORTSCROLL_FELDIP:
            case ItemID.TELEPORTSCROLL_GUTHIXIAN_TEMPLE:
            case ItemID.TELEPORTSCROLL_LUMBERYARD:
            case ItemID.TELEPORTSCROLL_LUNARISLE:
            case ItemID.TELEPORTSCROLL_MORTTON:
            case ItemID.TELEPORTSCROLL_MOSLES:
            case ItemID.TELEPORTSCROLL_NARDAH:
            case ItemID.TELEPORTSCROLL_PESTCONTROL:
            case ItemID.TELEPORTSCROLL_PISCATORIS:
            case ItemID.TELEPORTSCROLL_REVENANTS:
            case ItemID.TELEPORTSCROLL_SPIDERCAVE:
            case ItemID.TELEPORTSCROLL_TAIBWO:
            case ItemID.TELEPORTSCROLL_WATSON:
            case ItemID.TELEPORTSCROLL_ZULANDRA:
            case ItemID.TELETAB_APE:
            case ItemID.TELETAB_BARROWS:
            case ItemID.TELETAB_BATTLEFRONT:
            case ItemID.TELETAB_CEMETERY:
            case ItemID.TELETAB_DRAYNOR:
            case ItemID.TELETAB_FENK:
            case ItemID.TELETAB_HARMONY:
            case ItemID.TELETAB_LUMBRIDGE:
            case ItemID.TELETAB_MIND_ALTAR:
            case ItemID.TELETAB_SALVE:
            case ItemID.TELETAB_WESTARDY:
            case ItemID.TRAIL_AMULET_OF_GLORY:
            case ItemID.VARLAMORE_MINING_TELEPORT:
            case ItemID.VEOS_KHAREDSTS_MEMOIRS:
            case ItemID.VIKING_ENCHANTED_STRUNG_LYRE:
            case ItemID.WEISS_TELEPORT_BASALT:
            case ItemID.WESTERN_BANNER_ELITE:
            case ItemID.WESTERN_BANNER_HARD:
            case ItemID.WILDERNESS_SWORD_ELITE:
            case ItemID.WILDERNESS_SWORD_HARD:
            case ItemID.XERIC_TALISMAN:
            case ItemID.XMAS17_TELETAB:
            case ItemID.XMAS19_TABLET_SCAPE_RUNE:
            case ItemID.ZEAH_BLESSING_EASY:
            case ItemID.ZEAH_BLESSING_ELITE:
            case ItemID.ZEAH_BLESSING_HARD:
            case ItemID.ZEAH_BLESSING_MEDIUM:
            //Partial matches
            case ItemID.SKILLCAPE_AD_TRIMMED:
            case ItemID.TRAIL_AMULET_OF_GLORY_1:
            case ItemID.TRAIL_AMULET_OF_GLORY_2:
            case ItemID.TRAIL_AMULET_OF_GLORY_3:
            case ItemID.TRAIL_AMULET_OF_GLORY_4:
            case ItemID.TRAIL_AMULET_OF_GLORY_5:
            case ItemID.TRAIL_AMULET_OF_GLORY_6:
            case ItemID.SKILLCAPE_CONSTRUCTION_TRIMMED:
            case ItemID.SKILLCAPE_CRAFTING_TRIMMED:
            case ItemID.PRIF_TELEPORT_SEED:
            case ItemID.SKILLCAPE_DEFENCE_TRIMMED:
            case ItemID.POH_AMULET_DIGSITE:
            case ItemID.SKILLCAPE_FARMING_TRIMMED:
            case ItemID.SKILLCAPE_FISHING_TRIMMED:
            case ItemID.INFERNAL_DEFENDER_GHOMMAL_5_TROUVER:
            case ItemID.INFERNAL_DEFENDER_GHOMMAL_6_TROUVER:
            case ItemID.SKILLCAPE_HUNTING_TRIMMED:
            case ItemID.BR_TABLET_ANCIENTS:
            case ItemID.SKILLCAPE_MAX_ANMA:
            case ItemID.SKILLCAPE_MAX_ASSEMBLER:
            case ItemID.SKILLCAPE_MAX_ASSEMBLER_BROKEN:
            case ItemID.SKILLCAPE_MAX_ASSEMBLER_MASORI:
            case ItemID.SKILLCAPE_MAX_ASSEMBLER_MASORI_BROKEN:
            case ItemID.SKILLCAPE_MAX_ASSEMBLER_MASORI_TROUVER:
            case ItemID.SKILLCAPE_MAX_ASSEMBLER_TROUVER:
            case ItemID.SKILLCAPE_MAX_DIZANAS:
            case ItemID.SKILLCAPE_MAX_DIZANAS_BROKEN:
            case ItemID.SKILLCAPE_MAX_DIZANAS_TROUVER:
            case ItemID.SKILLCAPE_MAX_FIRECAPE_BROKEN:
            case ItemID.SKILLCAPE_MAX_FIRECAPE_DUMMY:
            case ItemID.SKILLCAPE_MAX_FIRECAPE_TROUVER:
            case ItemID.SKILLCAPE_MAX_GUTHIX:
            case ItemID.SKILLCAPE_MAX_GUTHIX2:
            case ItemID.SKILLCAPE_MAX_GUTHIX2_BROKEN:
            case ItemID.SKILLCAPE_MAX_GUTHIX2_TROUVER:
            case ItemID.SKILLCAPE_MAX_INFERNALCAPE:
            case ItemID.SKILLCAPE_MAX_INFERNALCAPE_BROKEN:
            case ItemID.SKILLCAPE_MAX_INFERNALCAPE_TROUVER:
            case ItemID.SKILLCAPE_MAX_SARADOMIN:
            case ItemID.SKILLCAPE_MAX_SARADOMIN2:
            case ItemID.SKILLCAPE_MAX_SARADOMIN2_BROKEN:
            case ItemID.SKILLCAPE_MAX_SARADOMIN2_TROUVER:
            case ItemID.SKILLCAPE_MAX_ZAMORAK:
            case ItemID.SKILLCAPE_MAX_ZAMORAK2:
            case ItemID.SKILLCAPE_MAX_ZAMORAK2_BROKEN:
            case ItemID.SKILLCAPE_MAX_ZAMORAK2_TROUVER:
            case ItemID.MUSIC_CAPE_TRIMMED:
            case ItemID.PHARAOHS_SCEPTRE:
            case ItemID.BH_IMBUE_RINGOFWEALTH:
            case ItemID.RING_OF_WEALTH_I1:
            case ItemID.RING_OF_WEALTH_I2:
            case ItemID.RING_OF_WEALTH_I3:
            case ItemID.RING_OF_WEALTH_I4:
            case ItemID.RING_OF_WEALTH_I5:
            case ItemID.SKILLCAPE_STRENGTH_TRIMMED:
            case ItemID.BOUNTY_TELEPORT_SCROLL:
            case ItemID.GAUNTLET_TELEPORT_CRYSTAL_HM:
            //Added manually
            case ItemID.BREW_RED_RUM:
            case ItemID.BREW_BLUE_RUM:
            case ItemID.PHARAOHS_SCEPTRE_CHARGED:
            case ItemID.WILDERNESS_SWORD_EASY:
            case ItemID.WILDERNESS_SWORD_MEDIUM:
            case ItemID.WESTERN_BANNER_EASY:
            case ItemID.WESTERN_BANNER_MEDIUM:
            case ItemID.ATJUN_GLOVES_EASY:
            case ItemID.ATJUN_GLOVES_MED:
            case ItemID.SEERS_HEADBAND_EASY:
            case ItemID.SEERS_HEADBAND_MEDIUM:
            case ItemID.LUMBRIDGE_RING_EASY:
            case ItemID.ECTOPHIAL:
            case ItemID.DESERT_AMULET_EASY:
            case ItemID.VARLAMORE_MINING_TELEPORT_1:
            case ItemID.VARLAMORE_MINING_TELEPORT_2:
            case ItemID.VARLAMORE_MINING_TELEPORT_3:
            case ItemID.VARLAMORE_MINING_TELEPORT_4:
            case ItemID.VARLAMORE_MINING_TELEPORT_5:
            case ItemID.VARLAMORE_MINING_TELEPORT_25:
            case ItemID.SKILLCAPE_MAX:
            case ItemID.SKILLCAPE_AD_HOOD:
                return true;
        }
        return false;
    }
}
